#!/usr/bin/env sh

line() {
	awk "NR == $1 {print}"
}

# get gpg version
gpg="gpg2"
command -v "$gpg" >/dev/null || gpg="gpg"
command -v "$gpg" >/dev/null || {
	echo "No GPG found!"
	exit 1
}

[ $# -lt 1 ] && {
	echo "Syntax: $0 <your@email.xyz>"
	exit 1
}

$gpg --list-key --with-fingerprint "$1" \
| line 2 \
| sed -E "s|^\s*(Key fingerprint = )?||; s|  | |" \
| tr " " "\n" \
| sed -E "s|(.)$|\1+1|" \
| { echo "ibase=16"; tee; } \
| bc \
| while read -r i; do line "$i" < "fingerprint_words.txt"; done \
| tr "\n" " " \
| head -c-1
echo
